apiVersion: v1
kind: Service
metadata:
  name: allure-svc
spec:
  selector:
    app: allure-service
  ports:
  - protocol: "TCP"
    port: 8000
    targetPort: 5050 
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: allure-service
spec:
  selector:
    matchLabels:
      app: allure-service
  replicas: 1
  template:
    metadata:
      labels:
        app: allure-service
    spec:
      containers:
      - name: allure-service 
        image: cfhayes/allure-svc:0.1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 5050
